<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TebuAlpukatSerai-WangiPadiKemiriKapulag_8c8cf8</name>
   <tag></tag>
   <elementGuidId>7eb694ca-c4c5-4d52-af25-cd253afeb542</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div[2]/div[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slider</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75d34623-509d-431e-a8c1-70d23e0ced41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>0b88811d-42b7-401a-ad1d-a65608d7eff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TebuAlpukatSerai-WangiPadiKemiriKapulagaTebuAlpukatSerai-WangiPadiKemiriKapulagaTebuAlpukatSerai-WangiPadiKemiriKapulaga</value>
      <webElementGuid>256d137c-c71b-401f-a9cd-18737d5a50d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;universal-wrap&quot;]/div[@class=&quot;agreepedia&quot;]/div[@class=&quot;konten&quot;]/div[@class=&quot;slider&quot;]</value>
      <webElementGuid>bacfa9d6-8f4c-4d2b-b6f6-63b77a5a2810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div[7]</value>
      <webElementGuid>84ae1847-4570-4d79-8a86-ea483fe94ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baca berbagai informasi terbaru seputar agrikultur untuk meningkatkan pemahamanmu!'])[3]/following::div[1]</value>
      <webElementGuid>7a384db9-df4e-42d6-b93a-576253b07563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info Budi Daya'])[2]/following::div[2]</value>
      <webElementGuid>9998fbc9-0f49-488d-a3de-32035f9322a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]</value>
      <webElementGuid>e964d860-9e4a-4e54-b703-e5eaf9a87b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TebuAlpukatSerai-WangiPadiKemiriKapulagaTebuAlpukatSerai-WangiPadiKemiriKapulagaTebuAlpukatSerai-WangiPadiKemiriKapulaga' or . = 'TebuAlpukatSerai-WangiPadiKemiriKapulagaTebuAlpukatSerai-WangiPadiKemiriKapulagaTebuAlpukatSerai-WangiPadiKemiriKapulaga')]</value>
      <webElementGuid>62cac515-b2cb-4418-b559-4923b848d162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
