<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Info Budi DayaBaca berbagai informasi t_455e19</name>
   <tag></tag>
   <elementGuidId>648471dd-e78a-4c66-b3d2-c30847e9d5f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-info-budidaya']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home-info-budidaya</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7c03f0a-6503-40f7-be36-0f1dae2cfc6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>6da4d2c8-d12d-4d33-b13b-9a734d4afd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-info-budidaya</value>
      <webElementGuid>6dd4bba0-ba30-4759-a157-01f30fe61ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Info Budi DayaBaca berbagai informasi terbaru seputar agrikultur untuk meningkatkan pemahamanmu!</value>
      <webElementGuid>ec3de12a-c539-4551-b506-c1e02abdc973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-info-budidaya&quot;)</value>
      <webElementGuid>9c05714c-4a65-4bfe-b5cc-155bf2f6c8ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='home-info-budidaya']</value>
      <webElementGuid>5cf6c236-4842-4254-85ba-e9d91b665e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div[6]</value>
      <webElementGuid>c910d8c8-da78-447c-b320-a28f1148a3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitur canggih Agreepedia akan segera hadir spesial buat kamu !'])[1]/following::div[2]</value>
      <webElementGuid>ec56bfe2-3d86-4140-b3f3-96d76cc95e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapet Ilmu + Sertifikat, Gratis!'])[1]/following::div[3]</value>
      <webElementGuid>89cd2781-c1aa-43cd-b1b9-c3e28a9693d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>1c34639b-2103-4ff8-a91e-863226ea573f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'home-info-budidaya' and (text() = 'Info Budi DayaBaca berbagai informasi terbaru seputar agrikultur untuk meningkatkan pemahamanmu!' or . = 'Info Budi DayaBaca berbagai informasi terbaru seputar agrikultur untuk meningkatkan pemahamanmu!')]</value>
      <webElementGuid>f54284b1-7dbc-41a6-8077-4c73eb1f7ef0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
