<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Baca berbagai informasi terbaru seputa_06fd24</name>
   <tag></tag>
   <elementGuidId>857be613-1c33-44e5-884e-d3b3a5fc8aef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-info-budidaya']/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>36ec07cd-18ce-4cc9-a237-84e8eaa7e415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baca berbagai informasi terbaru seputar agrikultur untuk meningkatkan pemahamanmu!</value>
      <webElementGuid>f15af3c1-f9d2-4d08-8ff9-a90b261f6ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-info-budidaya&quot;)/div[2]/span[1]</value>
      <webElementGuid>a371d0e1-8620-412d-b99e-b134cd8faf57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-info-budidaya']/div[2]/span</value>
      <webElementGuid>04eca913-c5e5-4894-9795-a20b6df07c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info Budi Daya'])[2]/following::span[1]</value>
      <webElementGuid>d5af58f1-8c5f-4e01-a30a-d0e39553ad47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitur canggih Agreepedia akan segera hadir spesial buat kamu !'])[1]/following::span[2]</value>
      <webElementGuid>3a9884f7-ea03-4111-a067-c1000fd8a725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tebu'])[1]/preceding::span[2]</value>
      <webElementGuid>c1e01c69-f244-4831-b427-e59a39882c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alpukat'])[1]/preceding::span[3]</value>
      <webElementGuid>ac3da070-cd49-441c-b13b-c10278aabd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/span</value>
      <webElementGuid>cbcd4869-7d13-43b3-af68-14189732e575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Baca berbagai informasi terbaru seputar agrikultur untuk meningkatkan pemahamanmu!' or . = 'Baca berbagai informasi terbaru seputar agrikultur untuk meningkatkan pemahamanmu!')]</value>
      <webElementGuid>48d2f345-0c21-472e-90d3-81ee62127d36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
