<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Entry</name>
   <tag></tag>
   <elementGuidId>d1ac3b7d-7804-44ce-a1fc-03e0d6a9b027</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex-x-between.kanan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6787955a-90bd-46a2-828a-1b1b5015df97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-x-between kanan</value>
      <webElementGuid>ff307d76-07a9-49d8-94c9-822cb516bb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MasukDaftar</value>
      <webElementGuid>717c1633-827f-46d6-a476-e490bea37171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;navbar&quot;]/div[@class=&quot;flex-x-between kanan&quot;]</value>
      <webElementGuid>fbb579cb-82a8-4537-b279-f20b3a3b49a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]</value>
      <webElementGuid>1a28c605-1761-4b6a-af0c-e3ea2bf88721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berita dan Kegiatan Agree'])[1]/following::div[1]</value>
      <webElementGuid>f3ad6d32-18e8-46f7-aa07-6c9a7cd3e38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan'])[1]/following::div[1]</value>
      <webElementGuid>215edf2f-554e-44de-8faf-cd3b5b8b74ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]</value>
      <webElementGuid>0738b1f7-6603-4e29-955a-6f08dbf7922f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MasukDaftar' or . = 'MasukDaftar')]</value>
      <webElementGuid>8a84f287-4188-4ad6-8fbb-cec7c619f81b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
