<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Artikel</name>
   <tag></tag>
   <elementGuidId>1c41ddc6-459d-463f-936c-3357394e0a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8e50135-7b16-4794-84be-06c07167bfff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/agreepedia#home-article</value>
      <webElementGuid>70052e10-a2dc-4dcc-b8ea-d4eeb7d27c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Artikel</value>
      <webElementGuid>9e2e435c-1800-40c3-b247-ec6a782e56c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;navbar3 flex-x-between navbar3-back2&quot;]/div[@class=&quot;flex-x-between tengah&quot;]/span[1]/a[1]</value>
      <webElementGuid>ab288bc1-5918-439b-b4f5-f270b643ba48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/span/a</value>
      <webElementGuid>38287e67-4913-41d0-8e76-5ae3911a7f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Artikel')]</value>
      <webElementGuid>f513d118-bee4-4e4c-ba6c-7206716ce64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Learning'])[1]/preceding::a[1]</value>
      <webElementGuid>acf65a42-db5e-4f7b-b737-94e3e5cd79f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info Budi Daya'])[1]/preceding::a[2]</value>
      <webElementGuid>f2b1f04c-1eff-4a39-9662-3e21f9c2ed70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/agreepedia#home-article')]</value>
      <webElementGuid>1300785c-ee77-4ac7-8bed-b6d9f29a4da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>21fff79d-e0f0-45b3-b740-b9b9d7cca6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/agreepedia#home-article' and (text() = 'Artikel' or . = 'Artikel')]</value>
      <webElementGuid>46a920a2-c009-4759-bcb3-f8a2fce343ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
