<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Fitur canggih Agreepedia akan segera ha_0f0c51</name>
   <tag></tag>
   <elementGuidId>ec489396-6b70-4759-8988-b6392d7ea704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div[2]/div[13]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f3c644e-13ea-4a29-8db0-9e5641a95d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fitur canggih Agreepedia akan segera hadir spesial buat kamu !</value>
      <webElementGuid>aada9ea4-41ec-4f2b-907a-90df84c14192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;universal-wrap&quot;]/div[@class=&quot;agreepedia&quot;]/div[@class=&quot;konten&quot;]/div[@class=&quot;iklan-background&quot;]/div[@class=&quot;iklan&quot;]/div[1]</value>
      <webElementGuid>ce171124-a8fd-4eae-959b-f6c1ecaf12f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div[13]/div/div</value>
      <webElementGuid>e1a41528-b023-4958-9077-d338eabff87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitur Canggih Agreepedia'])[1]/following::div[1]</value>
      <webElementGuid>05606bc2-63b2-411d-938a-28538a0a94c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitur canggih dari Agree untuk tingkatkan proses budidaya kamu'])[1]/following::div[3]</value>
      <webElementGuid>74e2c502-6952-479f-ae9b-3c407c1c733f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayo Daftar Agreepedia Sekarang'])[1]/preceding::div[1]</value>
      <webElementGuid>08ed7aca-89c7-4bfe-bd05-0879bf4e2cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div</value>
      <webElementGuid>cb5d8c5a-2bf9-4272-940c-493a17238e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Fitur canggih Agreepedia akan segera hadir spesial buat kamu !' or . = 'Fitur canggih Agreepedia akan segera hadir spesial buat kamu !')]</value>
      <webElementGuid>9eab1f5a-7739-4303-b042-5c92c8ee3e0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
