<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aplikasi AgreepediaFitur canggih dari A_f36047</name>
   <tag></tag>
   <elementGuidId>4f9ce907-1f8a-4051-9bf9-7c95becafe01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-aplikasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home-aplikasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1fc29083-49aa-473a-a3e6-9c558ada94f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>5892a006-283b-4b30-b361-3c2d9d4fa9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-aplikasi</value>
      <webElementGuid>4f8c505c-680d-4d37-b18c-0b563203af4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aplikasi AgreepediaFitur canggih dari Agree untuk tingkatkan proses budidaya kamu</value>
      <webElementGuid>eab9187a-d115-4e31-9660-e86e16a11b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-aplikasi&quot;)</value>
      <webElementGuid>0f9af26f-fba6-41ed-acc1-43fbb373ddf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='home-aplikasi']</value>
      <webElementGuid>842ad741-5530-4ced-a1d1-7f2eb72d1375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div[12]</value>
      <webElementGuid>af194de6-3467-4734-ad06-aa9ab070a3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitur Forum akan segera hadir, tunggu ya!'])[1]/following::div[2]</value>
      <webElementGuid>2746432d-d445-4be5-9185-075bc9653a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buka forum diskusimu sendiri dan bangun komunitas pertanian bersama penggiat agrikultur'])[1]/following::div[3]</value>
      <webElementGuid>1eaae031-7c9c-4cf4-b117-d874b95892fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[12]</value>
      <webElementGuid>69dc351c-c745-4047-9adc-4fb7d760f86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'home-aplikasi' and (text() = 'Aplikasi AgreepediaFitur canggih dari Agree untuk tingkatkan proses budidaya kamu' or . = 'Aplikasi AgreepediaFitur canggih dari Agree untuk tingkatkan proses budidaya kamu')]</value>
      <webElementGuid>5f1386bb-ba12-4865-bb58-bbbaf616f058</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
