<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pengguna Basic</name>
   <tag></tag>
   <elementGuidId>0d40b0c2-3a6d-4bcd-b3d5-163d62c52b13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-register']/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.basic</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b3649532-0007-4e76-afb7-c826f234d058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>basic</value>
      <webElementGuid>384c7018-a7dd-4cc2-a790-838b0f93117c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pengguna Basic</value>
      <webElementGuid>85866f02-d0c6-4ba5-b5bb-168f18de6d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-register&quot;)/div[1]/span[@class=&quot;basic&quot;]</value>
      <webElementGuid>b7ae8453-ce4b-4e77-b85e-5775583426b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-register']/div/span[2]</value>
      <webElementGuid>9275b6b2-a199-429f-9290-cb93ad55b47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengguna Expert'])[1]/following::span[1]</value>
      <webElementGuid>7c748fcc-d42b-4f0d-8671-f51c2791b350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih cara daftarmu, semua ada benefitnya, gabung ke komunitas Agrikultur terbesar di Indonesia!'])[1]/following::span[2]</value>
      <webElementGuid>bc28964d-b459-4cff-a580-ad16e0d29f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PENGGUNA BASIC'])[1]/preceding::span[1]</value>
      <webElementGuid>bd0964c4-cabe-4478-845c-cf98957e166c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayo Berkontribusi Kembangkan Agrikultur Indonesia!'])[1]/preceding::span[2]</value>
      <webElementGuid>81085266-9745-44d9-a7ff-9b626ad78c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div[3]/div/span[2]</value>
      <webElementGuid>d46cd74d-b0d8-48c5-8fb3-383e9b85ba85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pengguna Basic' or . = 'Pengguna Basic')]</value>
      <webElementGuid>cf2020c5-ae35-4163-b3f0-b7f94d7dadd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
