<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih cara daftarmu, semua ada benefit_ef5279</name>
   <tag></tag>
   <elementGuidId>f4951f59-6019-4608-a1d6-d7ad3e377739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-register']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a964db6a-95ae-496b-9720-30ced2d7fb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih cara daftarmu, semua ada benefitnya, gabung ke komunitas Agrikultur terbesar di Indonesia!</value>
      <webElementGuid>37287442-b896-4040-9064-dc170985dd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-register&quot;)/span[2]</value>
      <webElementGuid>4774def3-b528-444b-b7e0-972f2144d98b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-register']/span[2]</value>
      <webElementGuid>550d1933-061b-4305-aa7b-e42bcaecb1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayo Daftar Agreepedia Sekarang'])[1]/following::span[1]</value>
      <webElementGuid>a9a4197f-6f15-4011-9c01-ed75bebe166f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitur canggih Agreepedia akan segera hadir spesial buat kamu !'])[2]/following::span[2]</value>
      <webElementGuid>fa01bd40-82d1-4786-8ad5-67a70b4e4718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengguna Expert'])[1]/preceding::span[1]</value>
      <webElementGuid>30ca2f15-e1cd-457b-9ac0-5f6d565ffb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengguna Basic'])[1]/preceding::span[2]</value>
      <webElementGuid>78b436bf-ce45-4341-aaaa-34b968a6d803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]</value>
      <webElementGuid>0d1a9bc0-5694-427e-979f-b9f0d7db4afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pilih cara daftarmu, semua ada benefitnya, gabung ke komunitas Agrikultur terbesar di Indonesia!' or . = 'Pilih cara daftarmu, semua ada benefitnya, gabung ke komunitas Agrikultur terbesar di Indonesia!')]</value>
      <webElementGuid>1579b104-31ed-41ba-89e4-fe0e33765b4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
