<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_navbar</name>
   <tag></tag>
   <elementGuidId>ede19092-d5f3-4092-b258-47a44483ef4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sidebar-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>714a7aed-bc7f-4388-9930-9cbd78562035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-2</value>
      <webElementGuid>04dc4bf6-7fb0-459a-ace5-2ebeb96dc8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard Navigasimva.loppies@gmail.com</value>
      <webElementGuid>30b7ddfd-384c-4e28-816a-93ebe243a965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;sidebar-2&quot;]</value>
      <webElementGuid>b8a04760-75f6-4f37-bcf3-4cc9e7bbfecb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]</value>
      <webElementGuid>98951038-ee02-479a-8044-69ac194e5130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forum'])[1]/following::div[1]</value>
      <webElementGuid>47231d85-d518-4b7a-9bbe-9422f3701a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Learning'])[1]/following::div[2]</value>
      <webElementGuid>6b4dc6fb-5654-4130-8baf-36a600644675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>6ae43bdd-59d6-41ed-9311-aa0244a018f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dashboard Navigasimva.loppies@gmail.com' or . = 'Dashboard Navigasimva.loppies@gmail.com')]</value>
      <webElementGuid>01060db8-81b0-4899-996d-f3871e117280</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
