<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_News Date</name>
   <tag></tag>
   <elementGuidId>ebb179b6-ebaa-480c-ba87-70902a5548a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;flex-bet&quot;]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>127cdb2c-536f-4ea2-9d35-2bad34fa17a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1671337317193</value>
      <webElementGuid>5eb784cd-6623-499e-ad35-fdc0b3ab6011</webElementGuid>
   </webElementProperties>
</WebElementEntity>
