<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_News Label</name>
   <tag></tag>
   <elementGuidId>8d770904-0def-47c4-9c92-b2926f041baf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;kol&quot;]/div[@class=&quot;flex&quot;]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>886940b4-2273-401d-9dfb-d8a92de01d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1671337156464</value>
      <webElementGuid>b69805f0-f61c-433a-ace1-dfb53db0d114</webElementGuid>
   </webElementProperties>
</WebElementEntity>
