<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login Card</name>
   <tag></tag>
   <elementGuidId>d336c2e6-8c48-4c64-8b0a-f073cf3d3b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.kontainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cb8c23cc-28a4-4cd6-97f9-2f3c9d9e2911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kontainer</value>
      <webElementGuid>81a007b5-fb50-48ea-bba0-6a29221cc0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginMasukkan Email dan Kata Sandi untuk masuk ke AgreeEmailKata SandiIngat SayaLupa Kata Sandi?MasukBelum punya akun? Daftar Sekarang </value>
      <webElementGuid>1568f6ef-ad59-4559-8f92-f11af50e1dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;login&quot;]/div[@class=&quot;kontainer&quot;]</value>
      <webElementGuid>2d2aab05-be6d-4ad3-ac3a-35a55e3805e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div</value>
      <webElementGuid>51d68fdb-62b0-4ff3-aac5-c49e62396c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali ke Beranda'])[1]/following::div[1]</value>
      <webElementGuid>905048ee-6806-4336-a194-a5b103bcf517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>002c578c-dae0-40fe-8c5e-b7bdf5e72292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LoginMasukkan Email dan Kata Sandi untuk masuk ke AgreeEmailKata SandiIngat SayaLupa Kata Sandi?MasukBelum punya akun? Daftar Sekarang ' or . = 'LoginMasukkan Email dan Kata Sandi untuk masuk ke AgreeEmailKata SandiIngat SayaLupa Kata Sandi?MasukBelum punya akun? Daftar Sekarang ')]</value>
      <webElementGuid>5ba670f9-620d-470a-b8b9-22c51c4fefd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
