<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_dashboard</name>
   <tag></tag>
   <elementGuidId>eb43da4f-6c0f-4a51-bc72-0a44b60df77c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.utama</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>049c2000-ad84-4b06-8d71-51353a9cb1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>utama</value>
      <webElementGuid>a7a03aa8-7b3d-4495-b933-30b100841c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selamat DatangDashboard satu pintu sebagai tempat kolaborasi dan interaksi seluruh pengguna ekosistem AgreePilih kerja sama dengan AgreePerusahaanMonitor bisnis pertanianmu dari meja kerjamuPenjualTemukan pembeli dari komoditasmu &amp; bertransaksiPembeliPenuhi Kebutuhan agrikultur Anda hingga skala besarKolaborasi dan Berbagi Bersama AgreeKamu siap menjelajah Agreepedia!Nikmati beragam artikel dan tingkatkan kemampuan agrikulturmuBuka AgreepediaArtikelBagikan informasi menarik kepada seluruh pengguna AgreeDigital LearningTingkatkan pengetahuan dan raih sertifikat melalui materi menarikForumIkut berbagi dan berinteraksi bersama ahli dan pengguna Agree lainnya</value>
      <webElementGuid>ae43b257-2bd3-4679-8256-1bdb0d4a9952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;dtp&quot;]/div[@class=&quot;utama&quot;]</value>
      <webElementGuid>75ae599b-a4cb-4aad-8010-a448e844e100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div</value>
      <webElementGuid>c9f29cd5-4a68-4bfc-b4d2-b7d94bb7349c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mva.loppies@gmail.com'])[1]/following::div[2]</value>
      <webElementGuid>be5c2a6a-0329-4abb-a5bf-06d798fa7576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard Navigasi'])[1]/following::div[4]</value>
      <webElementGuid>3244c1f9-c8d1-40a3-b252-14758c8fb7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div</value>
      <webElementGuid>4ebaa147-ff82-4db3-8d85-010406c3abe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Selamat DatangDashboard satu pintu sebagai tempat kolaborasi dan interaksi seluruh pengguna ekosistem AgreePilih kerja sama dengan AgreePerusahaanMonitor bisnis pertanianmu dari meja kerjamuPenjualTemukan pembeli dari komoditasmu &amp; bertransaksiPembeliPenuhi Kebutuhan agrikultur Anda hingga skala besarKolaborasi dan Berbagi Bersama AgreeKamu siap menjelajah Agreepedia!Nikmati beragam artikel dan tingkatkan kemampuan agrikulturmuBuka AgreepediaArtikelBagikan informasi menarik kepada seluruh pengguna AgreeDigital LearningTingkatkan pengetahuan dan raih sertifikat melalui materi menarikForumIkut berbagi dan berinteraksi bersama ahli dan pengguna Agree lainnya' or . = 'Selamat DatangDashboard satu pintu sebagai tempat kolaborasi dan interaksi seluruh pengguna ekosistem AgreePilih kerja sama dengan AgreePerusahaanMonitor bisnis pertanianmu dari meja kerjamuPenjualTemukan pembeli dari komoditasmu &amp; bertransaksiPembeliPenuhi Kebutuhan agrikultur Anda hingga skala besarKolaborasi dan Berbagi Bersama AgreeKamu siap menjelajah Agreepedia!Nikmati beragam artikel dan tingkatkan kemampuan agrikulturmuBuka AgreepediaArtikelBagikan informasi menarik kepada seluruh pengguna AgreeDigital LearningTingkatkan pengetahuan dan raih sertifikat melalui materi menarikForumIkut berbagi dan berinteraksi bersama ahli dan pengguna Agree lainnya')]</value>
      <webElementGuid>1f43a307-1c77-4e77-a01f-d21cb9fafcdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
