<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kembali ke Beranda</name>
   <tag></tag>
   <elementGuidId>d04ea24a-8132-4f8e-91e6-6379da20ffa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.beranda</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfe57d3d-cb52-4693-b456-b31bb6a4e385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>beranda</value>
      <webElementGuid>383aa7de-1828-4ed4-a2aa-7f0c477e5fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kembali ke Beranda</value>
      <webElementGuid>6f5141c4-9158-4e37-bb4f-646d779d6fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;login&quot;]/a[@class=&quot;link&quot;]/div[@class=&quot;beranda&quot;]</value>
      <webElementGuid>b88315db-0fe2-42ba-8b61-65482a07250b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/a/div</value>
      <webElementGuid>d31f523d-f162-42b9-98d7-04424c603ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/preceding::div[1]</value>
      <webElementGuid>18ce5f40-ecdb-4982-9f05-c88bd2d2c311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>449da352-0872-4ea2-a9d6-fef9a95ccd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kembali ke Beranda' or . = 'Kembali ke Beranda')]</value>
      <webElementGuid>467bae8b-e274-4461-97ae-41af329ad0f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
