<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Forum AgreepediaDiskusikan dan tanyakan_dd6b2e</name>
   <tag></tag>
   <elementGuidId>51a24665-439e-4dbf-b513-3d52d3a270c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-forum']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home-forum</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>080ad4bd-bd01-4e35-a036-599e17d9003d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>77cc4142-f3cd-4f98-946b-3afa199e09e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-forum</value>
      <webElementGuid>bc4d4962-2790-45b4-a9fd-4a1924ecc730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forum AgreepediaDiskusikan dan tanyakan permasalahan agrikultur kamu kepada ahli di Agreepedia</value>
      <webElementGuid>3d9bf910-3969-41f3-83a3-b03ae9ad1e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-forum&quot;)</value>
      <webElementGuid>d15b46b6-f8f6-4290-b74d-4b0430d5ac88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='home-forum']</value>
      <webElementGuid>dfea9cc0-7551-4e44-8c3a-085967d7ec93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div[9]</value>
      <webElementGuid>ce1ffbc9-1206-481e-ba2e-d47524d9401c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kapulaga'])[3]/following::div[2]</value>
      <webElementGuid>cf82bfb8-dc33-416f-9a30-d883cbc7592b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kemiri'])[3]/following::div[3]</value>
      <webElementGuid>8f0cb208-7466-43eb-b210-a8aa1d1e03c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]</value>
      <webElementGuid>b994a317-afb5-4ba3-9d4f-3c45d15e860f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'home-forum' and (text() = 'Forum AgreepediaDiskusikan dan tanyakan permasalahan agrikultur kamu kepada ahli di Agreepedia' or . = 'Forum AgreepediaDiskusikan dan tanyakan permasalahan agrikultur kamu kepada ahli di Agreepedia')]</value>
      <webElementGuid>6048dfa3-d0b3-4f85-a58e-b8bd3c3f997c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
