<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Digital LearningBaca berbagai informasi_9e73f3</name>
   <tag></tag>
   <elementGuidId>7d4b2916-4bc5-47a5-bacf-29779c87cc56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-digital-learning']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home-digital-learning</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e015fcb-ac66-4861-b6d4-e6902722751f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>0f0d6a96-a36c-44fe-ba65-8b801ad934c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-digital-learning</value>
      <webElementGuid>6cc8afc0-777f-4dac-90f2-2673352a1177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Digital LearningBaca berbagai informasi terbaru seputar agrikultur untuk meningkatkan pemahamanmu!</value>
      <webElementGuid>ee401af0-0211-4cd5-815c-cd0d5f2f63f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-digital-learning&quot;)</value>
      <webElementGuid>0cb74142-5182-4a5f-ae96-d562b236d29c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='home-digital-learning']</value>
      <webElementGuid>908c9921-a05a-44bb-a72a-760716de26df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div[3]</value>
      <webElementGuid>03b71b03-c21e-4e99-988d-3a92f502ed0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sema Seoyardi'])[1]/following::div[1]</value>
      <webElementGuid>7a2e2270-835d-4fd8-8bf9-2d82b98e32f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agribisnis'])[2]/following::div[2]</value>
      <webElementGuid>cee42608-a520-42aa-b0b6-445d6f73d13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div[2]/div[3]</value>
      <webElementGuid>b203329f-7f59-4e64-a0cb-29dccc4266e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'home-digital-learning' and (text() = 'Digital LearningBaca berbagai informasi terbaru seputar agrikultur untuk meningkatkan pemahamanmu!' or . = 'Digital LearningBaca berbagai informasi terbaru seputar agrikultur untuk meningkatkan pemahamanmu!')]</value>
      <webElementGuid>9a206af9-c66c-461f-a312-69c63d01c04d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
