<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_login</name>
   <tag></tag>
   <elementGuidId>414bd2d1-9732-41ac-a635-0482a53ed009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.kontainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f8a61de-f5e0-417a-b801-3d8a805fc4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kontainer</value>
      <webElementGuid>8b6998ce-02ff-4354-8268-d90c135f8070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginMasukkan Email dan Kata Sandi untuk masuk ke AgreeEmailKata SandiIngat SayaLupa Kata Sandi?MasukBelum punya akun? Daftar Sekarang </value>
      <webElementGuid>d8b1d85d-127e-4ff1-91cc-757c12d2f3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;login&quot;]/div[@class=&quot;kontainer&quot;]</value>
      <webElementGuid>546375ff-cfb5-47a9-ade3-2da93a439618</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div</value>
      <webElementGuid>46a64a70-7023-4e54-afb6-68f0aad5fa64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali ke Beranda'])[1]/following::div[1]</value>
      <webElementGuid>0817dd39-5325-4e76-b743-94759b84813d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>ef700890-3b5e-4384-a7ea-7020f7c6b3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LoginMasukkan Email dan Kata Sandi untuk masuk ke AgreeEmailKata SandiIngat SayaLupa Kata Sandi?MasukBelum punya akun? Daftar Sekarang ' or . = 'LoginMasukkan Email dan Kata Sandi untuk masuk ke AgreeEmailKata SandiIngat SayaLupa Kata Sandi?MasukBelum punya akun? Daftar Sekarang ')]</value>
      <webElementGuid>97bebdfa-2459-4d71-96d0-d166e756859f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
