<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_profil</name>
   <tag></tag>
   <elementGuidId>b51018a9-5a2a-4ad6-8a1e-bd90b11ece30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pratinjau</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c84a816-2a92-4c1b-b3b6-afdc351cfedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pratinjau</value>
      <webElementGuid>14009a15-83d7-4309-b7d5-ea888bd1e494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Foto ProfileUpload Foto ProfileMaksimal foto 1 MB dengan eksistensi JPEG, JPG, atau PNGNama LengkapPekerjaanUpdate ProfileSilahkan melengkapi Profil Anda untuk mendapatkan Keuntungan yang lebih banyak dari Fitur Agreepedia</value>
      <webElementGuid>9968ce73-678b-4e0f-9bc1-2aa5e1ec9025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;propail&quot;]/div[@class=&quot;tambah4&quot;]/div[@class=&quot;pratinjau&quot;]</value>
      <webElementGuid>750d9668-c71e-4098-bf90-c4843eb51516</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div</value>
      <webElementGuid>4eb3c065-dbe0-4494-b47d-6fe4bcb73ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mva.loppies@gmail.com'])[1]/following::div[3]</value>
      <webElementGuid>7adb65d9-b2f7-4b30-a624-cfc43a05354e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard Navigasi'])[1]/following::div[5]</value>
      <webElementGuid>094bc573-2603-468b-bfdd-a5f2575ce9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div</value>
      <webElementGuid>f4a60482-2f87-410f-9be0-eded4eef566c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Foto ProfileUpload Foto ProfileMaksimal foto 1 MB dengan eksistensi JPEG, JPG, atau PNGNama LengkapPekerjaanUpdate ProfileSilahkan melengkapi Profil Anda untuk mendapatkan Keuntungan yang lebih banyak dari Fitur Agreepedia' or . = 'Foto ProfileUpload Foto ProfileMaksimal foto 1 MB dengan eksistensi JPEG, JPG, atau PNGNama LengkapPekerjaanUpdate ProfileSilahkan melengkapi Profil Anda untuk mendapatkan Keuntungan yang lebih banyak dari Fitur Agreepedia')]</value>
      <webElementGuid>dc092e75-267e-473e-8031-41217c1c4332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
